services:
  chatbot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: multi-task-chatbot
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - PORT=7860
      - SERVER_NAME=0.0.0.0
      - DEBUG=${DEBUG-0}
      - GRADIO_SHARE=0
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      
      # HTTP router (for traffic from Nginx cache to Traefik's port 80)
      # This also handles the HTTP-to-HTTPS redirect within Traefik
      - "traefik.http.routers.chatbot-http.rule=Host(`aichat.sourav.app`) || Host(`www.aichat.sourav.app`)"
      - "traefik.http.routers.chatbot-http.entrypoints=web"
      # - "traefik.http.routers.chatbot-http.middlewares=traefik-redirect-to-https"
      # - "traefik.http.routers.chatbot-http.middlewares=https-redirect"
      
      # HTTPS router (for traffic from Nginx SSL Passthrough to Traefik's port 443)
      - "traefik.http.routers.chatbot-https.rule=Host(`aichat.sourav.app`) || Host(`www.aichat.sourav.app`)"
      - "traefik.http.routers.chatbot-https.entrypoints=websecure"
      - "traefik.http.routers.chatbot-https.tls=true"
      - 'traefik.http.routers.chatbot-https.tls.certresolver=cloudflare'

      # Explicitly define the port
      - "traefik.http.services.chatbot-https.loadbalancer.server.port=7860"
    restart: unless-stopped

networks:
  frontend:
    external: true

secrets:
  tavily_api_key:
    file: ./secrets/tavily_api_key

